name: Build Saltwater

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  saltwater:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v3.9.0
        with:
          java-version: 8
          distribution: adopt
          java-package: jre
          
      - name: Set up structure
        run: |
          wget https://github.com/patataofcourse/Deckompiler/releases/download/v0.2.1/Deckompiler-linux.zip
          wget https://github.com/rhmodding/Tickompiler/releases/download/v1.10.0-hotfix/tickompiler.jar
          unzip Deckompiler-linux.zip 
          chmod u+x deckompiler
          mkdir -p out
          sed -r -i 's/#index (0x[0-9A-F]+)/#index 0x10B/' tickflow/remixENDLESS.tickflow
          
      - name: Build release btk
        run: |
          sed -i s/loadGamesLite.tickflow/loadGames.tickflow/ tickflow/remixENDLESS.tickflow
          sed -i s/loadGamesLite.tickflow/loadGames.tickflow/ tickflow/remixENDLESSGate1.tickflow
          sed -i s/loadGamesLite.tickflow/loadGames.tickflow/ tickflow/remixENDLESSGate2.tickflow
          sed -i s/loadGamesLite.tickflow/loadGames.tickflow/ tickflow/remixENDLESSGate3.tickflow
          java -jar tickompiler.jar c tickflow/ bin/
          ./deckompiler btks bin/remixENDLESS.bin out/remixENDLESS.btk bin/remixENDLESS.tempo
          ./deckompiler btks bin/remixENDLESSGate1.bin out/remixENDLESSGate1.btk bin/remixENDLESS.tempo
          ./deckompiler btks bin/remixENDLESSGate2.bin out/remixENDLESSGate2.btk bin/remixENDLESS.tempo
          ./deckompiler btks bin/remixENDLESSGate3.bin out/remixENDLESSGate3.btk bin/remixENDLESS.tempo
          
      - name: Build release btk lite
        run: |
          sed -i s/loadGames.tickflow/loadGamesLite.tickflow/ tickflow/remixENDLESS.tickflow
          sed -i s/loadGames.tickflow/loadGamesLite.tickflow/ tickflow/remixENDLESSGate1.tickflow
          sed -i s/loadGames.tickflow/loadGamesLite.tickflow/ tickflow/remixENDLESSGate2.tickflow
          sed -i s/loadGames.tickflow/loadGamesLite.tickflow/ tickflow/remixENDLESSGate3.tickflow
          java -jar tickompiler.jar c tickflow/ bin/
          ./deckompiler btks bin/remixENDLESS.bin out/remixENDLESS-lite.btk bin/remixENDLESS.tempo
          ./deckompiler btks bin/remixENDLESSGate1.bin out/remixENDLESSGate1-lite.btk bin/remixENDLESS.tempo
          ./deckompiler btks bin/remixENDLESSGate2.bin out/remixENDLESSGate2-lite.btk bin/remixENDLESS.tempo
          ./deckompiler btks bin/remixENDLESSGate3.bin out/remixENDLESSGate3-lite.btk bin/remixENDLESS.tempo

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Latest Saltwater btks
          path: out/
          
  full-mod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v3.9.0
        with:
          java-version: 8
          distribution: adopt
          java-package: jre
          
      - name: Set up RomFS structure
        run: |
          mkdir -p out/
          cd romfs
          cp -r ./* ../out/
          cd ../romfs-lite
          cp -r ./* ../out/

      - name: Set up structure
        run: |
          wget https://github.com/patataofcourse/Deckompiler/releases/download/v0.2.1/Deckompiler-linux.zip
          wget https://github.com/rhmodding/Tickompiler/releases/download/v1.10.0-hotfix/tickompiler.jar
          unzip Deckompiler-linux.zip 
          chmod u+x deckompiler
          sed -r -i 's/#index (0x[0-9A-F]+)/#index 0x10B/' tickflow/remixENDLESS.tickflow
          
      - name: Build release btk
        run: |
          sed -i s/loadGamesLite.tickflow/loadGames.tickflow/ tickflow/remixENDLESS.tickflow
          sed -i s/loadGamesLite.tickflow/loadGames.tickflow/ tickflow/remixENDLESSGate1.tickflow
          sed -i s/loadGamesLite.tickflow/loadGames.tickflow/ tickflow/remixENDLESSGate2.tickflow
          sed -i s/loadGamesLite.tickflow/loadGames.tickflow/ tickflow/remixENDLESSGate3.tickflow
          java -jar tickompiler.jar c tickflow/ bin/
          ./deckompiler btks bin/remixENDLESS.bin out/remixENDLESS.btk bin/remixENDLESS.tempo
          ./deckompiler btks bin/remixENDLESSGate1.bin out/remixENDLESSGate1.btk bin/remixENDLESS.tempo
          ./deckompiler btks bin/remixENDLESSGate2.bin out/remixENDLESSGate2.btk bin/remixENDLESS.tempo
          ./deckompiler btks bin/remixENDLESSGate3.bin out/remixENDLESSGate3.btk bin/remixENDLESS.tempo
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Endless Remix (Saltwater)
          path: out/
          
  lite-mod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v3.9.0
        with:
          java-version: 8
          distribution: adopt
          java-package: jre
          
      - name: Set up RomFS structure
        run: |
          mkdir -p out/
          cd romfs-lite
          cp -r ./* ../out/

      - name: Set up structure
        run: |
          wget https://github.com/patataofcourse/Deckompiler/releases/download/v0.2.1/Deckompiler-linux.zip
          wget https://github.com/rhmodding/Tickompiler/releases/download/v1.10.0-hotfix/tickompiler.jar
          unzip Deckompiler-linux.zip 
          chmod u+x deckompiler
          sed -r -i 's/#index (0x[0-9A-F]+)/#index 0x10B/' tickflow/remixENDLESS.tickflow
          
      - name: Build release btk
        run: |
          sed -i s/loadGames.tickflow/loadGamesLite.tickflow/ tickflow/remixENDLESS.tickflow
          sed -i s/loadGames.tickflow/loadGamesLite.tickflow/ tickflow/remixENDLESS.tickflow
          sed -i s/loadGames.tickflow/loadGamesLite.tickflow/ tickflow/remixENDLESSGate1.tickflow
          sed -i s/loadGames.tickflow/loadGamesLite.tickflow/ tickflow/remixENDLESSGate2.tickflow
          sed -i s/loadGames.tickflow/loadGamesLite.tickflow/ tickflow/remixENDLESSGate3.tickflow
          java -jar tickompiler.jar c tickflow/ bin/
          ./deckompiler btks bin/remixENDLESS.bin out/remixENDLESS.btk bin/remixENDLESS.tempo
          ./deckompiler btks bin/remixENDLESSGate1.bin out/remixENDLESSGate1.btk bin/remixENDLESS.tempo
          ./deckompiler btks bin/remixENDLESSGate2.bin out/remixENDLESSGate2.btk bin/remixENDLESS.tempo
          ./deckompiler btks bin/remixENDLESSGate3.bin out/remixENDLESSGate3.btk bin/remixENDLESS.tempo
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Endless Remix - Lite (Saltwater)
          path: out/